from __future__ import print_function, division

from types import FunctionType

from sympy.core.symbol import _uniquely_named_symbol
from sympy.core.sympify import _sympify
from sympy.polys import cancel, PurePoly
from sympy.simplify.simplify import simplify

from .common import MatrixCommon, NonSquareMatrixError
from .utilities import \
    _is_zero_after_expand_mul, _iszero, _find_reasonable_pivot


class MatrixDeterminant(MatrixCommon):
    """Provides basic matrix determinant operations.
    Should not be instantiated directly."""

    def _eval_berkowitz_toeplitz_matrix(self):
        """Return (A,T) where T the Toeplitz matrix used in the Berkowitz algorithm
        corresponding to ``self`` and A is the first principal submatrix."""

        # the 0 x 0 case is trivial
        if self.rows == 0 and self.cols == 0:
            return self._new(1,1, [self.one])

        #
        # Partition self = [ a_11  R ]
        #                  [ C     A ]
        #

        a, R = self[0,0],   self[0, 1:]
        C, A = self[1:, 0], self[1:,1:]

        #
        # The Toeplitz matrix looks like
        #
        #  [ 1                                     ]
        #  [ -a         1                          ]
        #  [ -RC       -a        1                 ]
        #  [ -RAC     -RC       -a       1         ]
        #  [ -RA**2C -RAC      -RC      -a       1 ]
        #  etc.

        # Compute the diagonal entries.
        # Because multiplying matrix times vector is so much
        # more efficient than matrix times matrix, recursively
        # compute -R * A**n * C.
        diags = [C]
        for i in range(self.rows - 2):
            diags.append(A * diags[i])
        diags = [(-R*d)[0, 0] for d in diags]
        diags = [self.one, -a] + diags

        def entry(i,j):
            if j > i:
                return self.zero
            return diags[i - j]

        toeplitz = self._new(self.cols + 1, self.rows, entry)
        return (A, toeplitz)

    def _eval_berkowitz_vector(self):
        """ Run the Berkowitz algorithm and return a vector whose entries
            are the coefficients of the characteristic polynomial of ``self``.

            Given N x N matrix, efficiently compute
            coefficients of characteristic polynomials of ``self``
            without division in the ground domain.

            This method is particularly useful for computing determinant,
            principal minors and characteristic polynomial when ``self``
            has complicated coefficients e.g. polynomials. Semi-direct
            usage of this algorithm is also important in computing
            efficiently sub-resultant PRS.

            Assuming that M is a square matrix of dimension N x N and
            I is N x N identity matrix, then the Berkowitz vector is
            an N x 1 vector whose entries are coefficients of the
            polynomial

                           charpoly(M) = det(t*I - M)

            As a consequence, all polynomials generated by Berkowitz
            algorithm are monic.

           For more information on the implemented algorithm refer to:

           [1] S.J. Berkowitz, On computing the determinant in small
               parallel time using a small number of processors, ACM,
               Information Processing Letters 18, 1984, pp. 147-150

           [2] M. Keber, Division-Free computation of sub-resultants
               using Bezout matrices, Tech. Report MPI-I-2006-1-006,
               Saarbrucken, 2006
        """

        # handle the trivial cases
        if self.rows == 0 and self.cols == 0:
            return self._new(1, 1, [self.one])
        elif self.rows == 1 and self.cols == 1:
            return self._new(2, 1, [self.one, -self[0,0]])

        submat, toeplitz = self._eval_berkowitz_toeplitz_matrix()
        return toeplitz * submat._eval_berkowitz_vector()

    def _eval_det_bareiss(self, iszerofunc=_is_zero_after_expand_mul):
        """Compute matrix determinant using Bareiss' fraction-free
        algorithm which is an extension of the well known Gaussian
        elimination method. This approach is best suited for dense
        symbolic matrices and will result in a determinant with
        minimal number of fractions. It means that less term
        rewriting is needed on resulting formulae.

        TODO: Implement algorithm for sparse matrices (SFF),
        http://www.eecis.udel.edu/~saunders/papers/sffge/it5.ps.
        """

        # Recursively implemented Bareiss' algorithm as per Deanna Richelle Leggett's
        # thesis http://www.math.usm.edu/perry/Research/Thesis_DRL.pdf
        def bareiss(mat, cumm=1):
            if mat.rows == 0:
                return mat.one
            elif mat.rows == 1:
                return mat[0, 0]

            # find a pivot and extract the remaining matrix
            # With the default iszerofunc, _find_reasonable_pivot slows down
            # the computation by the factor of 2.5 in one test.
            # Relevant issues: #10279 and #13877.
            pivot_pos, pivot_val, _, _ = _find_reasonable_pivot(mat[:, 0],
                                         iszerofunc=iszerofunc)
            if pivot_pos is None:
                return mat.zero

            # if we have a valid pivot, we'll do a "row swap", so keep the
            # sign of the det
            sign = (-1) ** (pivot_pos % 2)

            # we want every row but the pivot row and every column
            rows = list(i for i in range(mat.rows) if i != pivot_pos)
            cols = list(range(mat.cols))
            tmp_mat = mat.extract(rows, cols)

            def entry(i, j):
                ret = (pivot_val*tmp_mat[i, j + 1] - mat[pivot_pos, j + 1]*tmp_mat[i, 0]) / cumm
                if not ret.is_Atom:
                    return cancel(ret)
                return ret

            return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)

        return cancel(bareiss(self))

    def _eval_det_berkowitz(self):
        """ Use the Berkowitz algorithm to compute the determinant."""
        berk_vector = self._eval_berkowitz_vector()
        return (-1)**(len(berk_vector) - 1) * berk_vector[-1]

    def _eval_det_lu(self, iszerofunc=_iszero, simpfunc=None):
        """ Computes the determinant of a matrix from its LU decomposition.
        This function uses the LU decomposition computed by
        LUDecomposition_Simple().

        The keyword arguments iszerofunc and simpfunc are passed to
        LUDecomposition_Simple().
        iszerofunc is a callable that returns a boolean indicating if its
        input is zero, or None if it cannot make the determination.
        simpfunc is a callable that simplifies its input.
        The default is simpfunc=None, which indicate that the pivot search
        algorithm should not attempt to simplify any candidate pivots.
        If simpfunc fails to simplify its input, then it must return its input
        instead of a copy."""

        if self.rows == 0:
            return self.one
            # sympy/matrices/tests/test_matrices.py contains a test that
            # suggests that the determinant of a 0 x 0 matrix is one, by
            # convention.

        lu, row_swaps = self.LUdecomposition_Simple(iszerofunc=iszerofunc, simpfunc=None)
        # P*A = L*U => det(A) = det(L)*det(U)/det(P) = det(P)*det(U).
        # Lower triangular factor L encoded in lu has unit diagonal => det(L) = 1.
        # P is a permutation matrix => det(P) in {-1, 1} => 1/det(P) = det(P).
        # LUdecomposition_Simple() returns a list of row exchange index pairs, rather
        # than a permutation matrix, but det(P) = (-1)**len(row_swaps).

        # Avoid forming the potentially time consuming  product of U's diagonal entries
        # if the product is zero.
        # Bottom right entry of U is 0 => det(A) = 0.
        # It may be impossible to determine if this entry of U is zero when it is symbolic.
        if iszerofunc(lu[lu.rows-1, lu.rows-1]):
            return self.zero

        # Compute det(P)
        det = -self.one if len(row_swaps)%2 else self.one

        # Compute det(U) by calculating the product of U's diagonal entries.
        # The upper triangular portion of lu is the upper triangular portion of the
        # U factor in the LU decomposition.
        for k in range(lu.rows):
            det *= lu[k, k]

        # return det(P)*det(U)
        return det

    def _eval_determinant(self):
        """Assumed to exist by matrix expressions; If we subclass
        MatrixDeterminant, we can fully evaluate determinants."""
        return self.det()

    def adjugate(self, method="berkowitz"):
        """Returns the adjugate, or classical adjoint, of
        a matrix.  That is, the transpose of the matrix of cofactors.


        https://en.wikipedia.org/wiki/Adjugate

        See Also
        ========

        cofactor_matrix
        transpose
        """
        return self.cofactor_matrix(method).transpose()

    def charpoly(self, x='lambda', simplify=simplify):
        """Computes characteristic polynomial det(x*I - self) where I is
        the identity matrix.

        A PurePoly is returned, so using different variables for ``x`` does
        not affect the comparison or the polynomials:

        Examples
        ========

        >>> from sympy import Matrix
        >>> from sympy.abc import x, y
        >>> A = Matrix([[1, 3], [2, 0]])
        >>> A.charpoly(x) == A.charpoly(y)
        True

        Specifying ``x`` is optional; a symbol named ``lambda`` is used by
        default (which looks good when pretty-printed in unicode):

        >>> A.charpoly().as_expr()
        lambda**2 - lambda - 6

        And if ``x`` clashes with an existing symbol, underscores will
        be prepended to the name to make it unique:

        >>> A = Matrix([[1, 2], [x, 0]])
        >>> A.charpoly(x).as_expr()
        _x**2 - _x - 2*x

        Whether you pass a symbol or not, the generator can be obtained
        with the gen attribute since it may not be the same as the symbol
        that was passed:

        >>> A.charpoly(x).gen
        _x
        >>> A.charpoly(x).gen == x
        False

        Notes
        =====

        The Samuelson-Berkowitz algorithm is used to compute
        the characteristic polynomial efficiently and without any
        division operations.  Thus the characteristic polynomial over any
        commutative ring without zero divisors can be computed.

        See Also
        ========

        det
        """

        if not self.is_square:
            raise NonSquareMatrixError()

        berk_vector = self._eval_berkowitz_vector()
        x = _uniquely_named_symbol(x, berk_vector)
        return PurePoly([simplify(a) for a in berk_vector], x)

    def cofactor(self, i, j, method="berkowitz"):
        """Calculate the cofactor of an element.

        See Also
        ========

        cofactor_matrix
        minor
        minor_submatrix
        """

        if not self.is_square or self.rows < 1:
            raise NonSquareMatrixError()

        return (-1)**((i + j) % 2) * self.minor(i, j, method)

    def cofactor_matrix(self, method="berkowitz"):
        """Return a matrix containing the cofactor of each element.

        See Also
        ========

        cofactor
        minor
        minor_submatrix
        adjugate
        """

        if not self.is_square or self.rows < 1:
            raise NonSquareMatrixError()

        return self._new(self.rows, self.cols,
                         lambda i, j: self.cofactor(i, j, method))

    def det(self, method="bareiss", iszerofunc=None):
        """Computes the determinant of a matrix.

        Parameters
        ==========

        method : string, optional
            Specifies the algorithm used for computing the matrix determinant.

            If the matrix is at most 3x3, a hard-coded formula is used and the
            specified method is ignored. Otherwise, it defaults to
            ``'bareiss'``.

            If it is set to ``'bareiss'``, Bareiss' fraction-free algorithm will
            be used.

            If it is set to ``'berkowitz'``, Berkowitz' algorithm will be used.

            Otherwise, if it is set to ``'lu'``, LU decomposition will be used.

            .. note::
                For backward compatibility, legacy keys like "bareis" and
                "det_lu" can still be used to indicate the corresponding
                methods.
                And the keys are also case-insensitive for now. However, it is
                suggested to use the precise keys for specifying the method.

        iszerofunc : FunctionType or None, optional
            If it is set to ``None``, it will be defaulted to ``_iszero`` if the
            method is set to ``'bareiss'``, and ``_is_zero_after_expand_mul`` if
            the method is set to ``'lu'``.

            It can also accept any user-specified zero testing function, if it
            is formatted as a function which accepts a single symbolic argument
            and returns ``True`` if it is tested as zero and ``False`` if it
            tested as non-zero, and also ``None`` if it is undecidable.

        Returns
        =======

        det : Basic
            Result of determinant.

        Raises
        ======

        ValueError
            If unrecognized keys are given for ``method`` or ``iszerofunc``.

        NonSquareMatrixError
            If attempted to calculate determinant from a non-square matrix.
        """

        # sanitize `method`
        method = method.lower()
        if method == "bareis":
            method = "bareiss"
        if method == "det_lu":
            method = "lu"
        if method not in ("bareiss", "berkowitz", "lu"):
            raise ValueError("Determinant method '%s' unrecognized" % method)

        if iszerofunc is None:
            if method == "bareiss":
                iszerofunc = _is_zero_after_expand_mul
            elif method == "lu":
                iszerofunc = _iszero
        elif not isinstance(iszerofunc, FunctionType):
            raise ValueError("Zero testing method '%s' unrecognized" % iszerofunc)

        # if methods were made internal and all determinant calculations
        # passed through here, then these lines could be factored out of
        # the method routines
        if not self.is_square:
            raise NonSquareMatrixError()

        n = self.rows
        if n == 0:
            return self.one
        elif n == 1:
            return self[0,0]
        elif n == 2:
            return self[0, 0] * self[1, 1] - self[0, 1] * self[1, 0]
        elif n == 3:
            return  (self[0, 0] * self[1, 1] * self[2, 2]
                   + self[0, 1] * self[1, 2] * self[2, 0]
                   + self[0, 2] * self[1, 0] * self[2, 1]
                   - self[0, 2] * self[1, 1] * self[2, 0]
                   - self[0, 0] * self[1, 2] * self[2, 1]
                   - self[0, 1] * self[1, 0] * self[2, 2])

        if method == "bareiss":
            return self._eval_det_bareiss(iszerofunc=iszerofunc)
        elif method == "berkowitz":
            return self._eval_det_berkowitz()
        elif method == "lu":
            return self._eval_det_lu(iszerofunc=iszerofunc)

    def minor(self, i, j, method="berkowitz"):
        """Return the (i,j) minor of ``self``.  That is,
        return the determinant of the matrix obtained by deleting
        the `i`th row and `j`th column from ``self``.

        See Also
        ========

        minor_submatrix
        cofactor
        det
        """

        if not self.is_square or self.rows < 1:
            raise NonSquareMatrixError()

        return self.minor_submatrix(i, j).det(method=method)

    def minor_submatrix(self, i, j):
        """Return the submatrix obtained by removing the `i`th row
        and `j`th column from ``self``.

        See Also
        ========

        minor
        cofactor
        """

        if i < 0:
            i += self.rows
        if j < 0:
            j += self.cols

        if not 0 <= i < self.rows or not 0 <= j < self.cols:
            raise ValueError("`i` and `j` must satisfy 0 <= i < ``self.rows`` "
                             "(%d)" % self.rows + "and 0 <= j < ``self.cols`` (%d)." % self.cols)

        rows = [a for a in range(self.rows) if a != i]
        cols = [a for a in range(self.cols) if a != j]
        return self.extract(rows, cols)
