
# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from antlr4 import *
from io import StringIO
from typing.io import TextIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write("\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2>")
        buf.write("\u0205\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4\7")
        buf.write("\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r\t\r")
        buf.write("\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22\4\23")
        buf.write("\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4\30\t\30")
        buf.write("\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35\t\35\4\36")
        buf.write("\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4$\t$\4%\t%")
        buf.write("\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t,\4-\t-\4.")
        buf.write("\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63\t\63\4\64")
        buf.write("\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\49\t9\4:\t:")
        buf.write("\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\3\2\3\2\3\3\6\3\u0083\n")
        buf.write("\3\r\3\16\3\u0084\3\3\3\3\3\4\3\4\3\5\3\5\3\6\3\6\3\7")
        buf.write("\3\7\3\b\3\b\3\t\3\t\3\n\3\n\3\13\3\13\3\f\3\f\3\r\3\r")
        buf.write("\3\16\3\16\3\17\3\17\3\17\3\17\3\17\3\20\3\20\3\20\3\20")
        buf.write("\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write("\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write("\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write("\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write("\3\20\3\20\3\20\3\20\3\20\3\20\3\20\5\20\u00db\n\20\3")
        buf.write("\21\3\21\3\21\3\21\3\21\3\22\3\22\3\22\3\22\3\22\3\23")
        buf.write("\3\23\3\23\3\23\3\23\3\23\3\24\3\24\3\24\3\24\3\24\3\25")
        buf.write("\3\25\3\25\3\25\3\26\3\26\3\26\3\26\3\26\3\27\3\27\3\27")
        buf.write("\3\27\3\27\3\30\3\30\3\30\3\30\3\30\3\31\3\31\3\31\3\31")
        buf.write("\3\31\3\32\3\32\3\32\3\32\3\32\3\33\3\33\3\33\3\33\3\33")
        buf.write("\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\35\3\35\3\35")
        buf.write("\3\35\3\35\3\35\3\35\3\35\3\36\3\36\3\36\3\36\3\36\3\36")
        buf.write("\3\36\3\36\3\37\3\37\3\37\3\37\3\37\3\37\3\37\3\37\3 ")
        buf.write("\3 \3 \3 \3 \3 \3 \3 \3!\3!\3!\3!\3!\3!\3!\3!\3\"\3\"")
        buf.write("\3\"\3\"\3\"\3\"\3#\3#\3#\3#\3#\3#\3$\3$\3$\3$\3$\3$\3")
        buf.write("%\3%\3%\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&\3&\3&\3&\3\'\3\'")
        buf.write("\3\'\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3(\3(\3(\3)\3)\3)\3")
        buf.write(")\3)\3)\3)\3*\3*\3*\3*\3*\3*\3+\3+\3+\3+\3+\3,\3,\3,\3")
        buf.write(",\3,\3,\3-\3-\3-\3-\3-\3-\3-\3.\3.\3.\3.\3.\3.\3.\3.\3")
        buf.write("/\3/\3/\3/\3/\3/\3/\3/\3\60\3\60\3\60\3\60\3\60\3\60\3")
        buf.write("\60\3\60\3\61\3\61\3\62\3\62\3\63\3\63\3\64\3\64\3\65")
        buf.write("\3\65\7\65\u01b5\n\65\f\65\16\65\u01b8\13\65\3\65\3\65")
        buf.write("\3\65\6\65\u01bd\n\65\r\65\16\65\u01be\5\65\u01c1\n\65")
        buf.write("\3\66\3\66\3\67\3\67\38\68\u01c8\n8\r8\168\u01c9\38\3")
        buf.write("8\38\38\38\78\u01d1\n8\f8\168\u01d4\138\38\78\u01d7\n")
        buf.write("8\f8\168\u01da\138\38\38\38\38\38\78\u01e1\n8\f8\168\u01e4")
        buf.write("\138\38\38\68\u01e8\n8\r8\168\u01e9\58\u01ec\n8\39\39")
        buf.write("\3:\3:\3;\3;\3;\3;\3;\3<\3<\3=\3=\3=\3=\3=\3>\3>\3?\3")
        buf.write("?\6?\u0202\n?\r?\16?\u0203\3\u01b6\2@\3\3\5\4\7\5\t\6")
        buf.write("\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31\16\33\17\35\20")
        buf.write("\37\21!\22#\23%\24\'\25)\26+\27-\30/\31\61\32\63\33\65")
        buf.write("\34\67\359\36;\37= ?!A\"C#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60")
        buf.write("_\61a\62c\63e\64g\2i\65k\66m\2o\67q8s9u:w;y<{=}>\3\2\5")
        buf.write("\5\2\13\f\17\17\"\"\4\2C\\c|\3\2\62;\2\u0211\2\3\3\2\2")
        buf.write("\2\2\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2")
        buf.write("\r\3\2\2\2\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25")
        buf.write("\3\2\2\2\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3")
        buf.write("\2\2\2\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2")
        buf.write("\'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2")
        buf.write("\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2\2\2")
        buf.write("9\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2")
        buf.write("\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2")
        buf.write("\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2")
        buf.write("\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3")
        buf.write("\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2i\3\2\2\2\2k")
        buf.write("\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2\2\2")
        buf.write("w\3\2\2\2\2y\3\2\2\2\2{\3\2\2\2\2}\3\2\2\2\3\177\3\2\2")
        buf.write("\2\5\u0082\3\2\2\2\7\u0088\3\2\2\2\t\u008a\3\2\2\2\13")
        buf.write("\u008c\3\2\2\2\r\u008e\3\2\2\2\17\u0090\3\2\2\2\21\u0092")
        buf.write("\3\2\2\2\23\u0094\3\2\2\2\25\u0096\3\2\2\2\27\u0098\3")
        buf.write("\2\2\2\31\u009a\3\2\2\2\33\u009c\3\2\2\2\35\u009e\3\2")
        buf.write("\2\2\37\u00da\3\2\2\2!\u00dc\3\2\2\2#\u00e1\3\2\2\2%\u00e6")
        buf.write("\3\2\2\2\'\u00ec\3\2\2\2)\u00f1\3\2\2\2+\u00f5\3\2\2\2")
        buf.write("-\u00fa\3\2\2\2/\u00ff\3\2\2\2\61\u0104\3\2\2\2\63\u0109")
        buf.write("\3\2\2\2\65\u010e\3\2\2\2\67\u0113\3\2\2\29\u011b\3\2")
        buf.write("\2\2;\u0123\3\2\2\2=\u012b\3\2\2\2?\u0133\3\2\2\2A\u013b")
        buf.write("\3\2\2\2C\u0143\3\2\2\2E\u0149\3\2\2\2G\u014f\3\2\2\2")
        buf.write("I\u0155\3\2\2\2K\u015d\3\2\2\2M\u0165\3\2\2\2O\u016d\3")
        buf.write("\2\2\2Q\u0173\3\2\2\2S\u017a\3\2\2\2U\u0180\3\2\2\2W\u0185")
        buf.write("\3\2\2\2Y\u018b\3\2\2\2[\u0192\3\2\2\2]\u019a\3\2\2\2")
        buf.write("_\u01a2\3\2\2\2a\u01aa\3\2\2\2c\u01ac\3\2\2\2e\u01ae\3")
        buf.write("\2\2\2g\u01b0\3\2\2\2i\u01b2\3\2\2\2k\u01c2\3\2\2\2m\u01c4")
        buf.write("\3\2\2\2o\u01eb\3\2\2\2q\u01ed\3\2\2\2s\u01ef\3\2\2\2")
        buf.write("u\u01f1\3\2\2\2w\u01f6\3\2\2\2y\u01f8\3\2\2\2{\u01fd\3")
        buf.write("\2\2\2}\u01ff\3\2\2\2\177\u0080\7.\2\2\u0080\4\3\2\2\2")
        buf.write("\u0081\u0083\t\2\2\2\u0082\u0081\3\2\2\2\u0083\u0084\3")
        buf.write("\2\2\2\u0084\u0082\3\2\2\2\u0084\u0085\3\2\2\2\u0085\u0086")
        buf.write("\3\2\2\2\u0086\u0087\b\3\2\2\u0087\6\3\2\2\2\u0088\u0089")
        buf.write("\7-\2\2\u0089\b\3\2\2\2\u008a\u008b\7/\2\2\u008b\n\3\2")
        buf.write("\2\2\u008c\u008d\7,\2\2\u008d\f\3\2\2\2\u008e\u008f\7")
        buf.write("\61\2\2\u008f\16\3\2\2\2\u0090\u0091\7*\2\2\u0091\20\3")
        buf.write("\2\2\2\u0092\u0093\7+\2\2\u0093\22\3\2\2\2\u0094\u0095")
        buf.write("\7}\2\2\u0095\24\3\2\2\2\u0096\u0097\7\177\2\2\u0097\26")
        buf.write("\3\2\2\2\u0098\u0099\7]\2\2\u0099\30\3\2\2\2\u009a\u009b")
        buf.write("\7_\2\2\u009b\32\3\2\2\2\u009c\u009d\7~\2\2\u009d\34\3")
        buf.write("\2\2\2\u009e\u009f\7^\2\2\u009f\u00a0\7n\2\2\u00a0\u00a1")
        buf.write("\7k\2\2\u00a1\u00a2\7o\2\2\u00a2\36\3\2\2\2\u00a3\u00a4")
        buf.write("\7^\2\2\u00a4\u00a5\7v\2\2\u00a5\u00db\7q\2\2\u00a6\u00a7")
        buf.write("\7^\2\2\u00a7\u00a8\7t\2\2\u00a8\u00a9\7k\2\2\u00a9\u00aa")
        buf.write("\7i\2\2\u00aa\u00ab\7j\2\2\u00ab\u00ac\7v\2\2\u00ac\u00ad")
        buf.write("\7c\2\2\u00ad\u00ae\7t\2\2\u00ae\u00af\7t\2\2\u00af\u00b0")
        buf.write("\7q\2\2\u00b0\u00db\7y\2\2\u00b1\u00b2\7^\2\2\u00b2\u00b3")
        buf.write("\7T\2\2\u00b3\u00b4\7k\2\2\u00b4\u00b5\7i\2\2\u00b5\u00b6")
        buf.write("\7j\2\2\u00b6\u00b7\7v\2\2\u00b7\u00b8\7c\2\2\u00b8\u00b9")
        buf.write("\7t\2\2\u00b9\u00ba\7t\2\2\u00ba\u00bb\7q\2\2\u00bb\u00db")
        buf.write("\7y\2\2\u00bc\u00bd\7^\2\2\u00bd\u00be\7n\2\2\u00be\u00bf")
        buf.write("\7q\2\2\u00bf\u00c0\7p\2\2\u00c0\u00c1\7i\2\2\u00c1\u00c2")
        buf.write("\7t\2\2\u00c2\u00c3\7k\2\2\u00c3\u00c4\7i\2\2\u00c4\u00c5")
        buf.write("\7j\2\2\u00c5\u00c6\7v\2\2\u00c6\u00c7\7c\2\2\u00c7\u00c8")
        buf.write("\7t\2\2\u00c8\u00c9\7t\2\2\u00c9\u00ca\7q\2\2\u00ca\u00db")
        buf.write("\7y\2\2\u00cb\u00cc\7^\2\2\u00cc\u00cd\7N\2\2\u00cd\u00ce")
        buf.write("\7q\2\2\u00ce\u00cf\7p\2\2\u00cf\u00d0\7i\2\2\u00d0\u00d1")
        buf.write("\7t\2\2\u00d1\u00d2\7k\2\2\u00d2\u00d3\7i\2\2\u00d3\u00d4")
        buf.write("\7j\2\2\u00d4\u00d5\7v\2\2\u00d5\u00d6\7c\2\2\u00d6\u00d7")
        buf.write("\7t\2\2\u00d7\u00d8\7t\2\2\u00d8\u00d9\7q\2\2\u00d9\u00db")
        buf.write("\7y\2\2\u00da\u00a3\3\2\2\2\u00da\u00a6\3\2\2\2\u00da")
        buf.write("\u00b1\3\2\2\2\u00da\u00bc\3\2\2\2\u00da\u00cb\3\2\2\2")
        buf.write("\u00db \3\2\2\2\u00dc\u00dd\7^\2\2\u00dd\u00de\7k\2\2")
        buf.write("\u00de\u00df\7p\2\2\u00df\u00e0\7v\2\2\u00e0\"\3\2\2\2")
        buf.write("\u00e1\u00e2\7^\2\2\u00e2\u00e3\7u\2\2\u00e3\u00e4\7w")
        buf.write("\2\2\u00e4\u00e5\7o\2\2\u00e5$\3\2\2\2\u00e6\u00e7\7^")
        buf.write("\2\2\u00e7\u00e8\7r\2\2\u00e8\u00e9\7t\2\2\u00e9\u00ea")
        buf.write("\7q\2\2\u00ea\u00eb\7f\2\2\u00eb&\3\2\2\2\u00ec\u00ed")
        buf.write("\7^\2\2\u00ed\u00ee\7n\2\2\u00ee\u00ef\7q\2\2\u00ef\u00f0")
        buf.write("\7i\2\2\u00f0(\3\2\2\2\u00f1\u00f2\7^\2\2\u00f2\u00f3")
        buf.write("\7n\2\2\u00f3\u00f4\7p\2\2\u00f4*\3\2\2\2\u00f5\u00f6")
        buf.write("\7^\2\2\u00f6\u00f7\7u\2\2\u00f7\u00f8\7k\2\2\u00f8\u00f9")
        buf.write("\7p\2\2\u00f9,\3\2\2\2\u00fa\u00fb\7^\2\2\u00fb\u00fc")
        buf.write("\7e\2\2\u00fc\u00fd\7q\2\2\u00fd\u00fe\7u\2\2\u00fe.\3")
        buf.write("\2\2\2\u00ff\u0100\7^\2\2\u0100\u0101\7v\2\2\u0101\u0102")
        buf.write("\7c\2\2\u0102\u0103\7p\2\2\u0103\60\3\2\2\2\u0104\u0105")
        buf.write("\7^\2\2\u0105\u0106\7e\2\2\u0106\u0107\7u\2\2\u0107\u0108")
        buf.write("\7e\2\2\u0108\62\3\2\2\2\u0109\u010a\7^\2\2\u010a\u010b")
        buf.write("\7u\2\2\u010b\u010c\7g\2\2\u010c\u010d\7e\2\2\u010d\64")
        buf.write("\3\2\2\2\u010e\u010f\7^\2\2\u010f\u0110\7e\2\2\u0110\u0111")
        buf.write("\7q\2\2\u0111\u0112\7v\2\2\u0112\66\3\2\2\2\u0113\u0114")
        buf.write("\7^\2\2\u0114\u0115\7c\2\2\u0115\u0116\7t\2\2\u0116\u0117")
        buf.write("\7e\2\2\u0117\u0118\7u\2\2\u0118\u0119\7k\2\2\u0119\u011a")
        buf.write("\7p\2\2\u011a8\3\2\2\2\u011b\u011c\7^\2\2\u011c\u011d")
        buf.write("\7c\2\2\u011d\u011e\7t\2\2\u011e\u011f\7e\2\2\u011f\u0120")
        buf.write("\7e\2\2\u0120\u0121\7q\2\2\u0121\u0122\7u\2\2\u0122:\3")
        buf.write("\2\2\2\u0123\u0124\7^\2\2\u0124\u0125\7c\2\2\u0125\u0126")
        buf.write("\7t\2\2\u0126\u0127\7e\2\2\u0127\u0128\7v\2\2\u0128\u0129")
        buf.write("\7c\2\2\u0129\u012a\7p\2\2\u012a<\3\2\2\2\u012b\u012c")
        buf.write("\7^\2\2\u012c\u012d\7c\2\2\u012d\u012e\7t\2\2\u012e\u012f")
        buf.write("\7e\2\2\u012f\u0130\7e\2\2\u0130\u0131\7u\2\2\u0131\u0132")
        buf.write("\7e\2\2\u0132>\3\2\2\2\u0133\u0134\7^\2\2\u0134\u0135")
        buf.write("\7c\2\2\u0135\u0136\7t\2\2\u0136\u0137\7e\2\2\u0137\u0138")
        buf.write("\7u\2\2\u0138\u0139\7g\2\2\u0139\u013a\7e\2\2\u013a@\3")
        buf.write("\2\2\2\u013b\u013c\7^\2\2\u013c\u013d\7c\2\2\u013d\u013e")
        buf.write("\7t\2\2\u013e\u013f\7e\2\2\u013f\u0140\7e\2\2\u0140\u0141")
        buf.write("\7q\2\2\u0141\u0142\7v\2\2\u0142B\3\2\2\2\u0143\u0144")
        buf.write("\7^\2\2\u0144\u0145\7u\2\2\u0145\u0146\7k\2\2\u0146\u0147")
        buf.write("\7p\2\2\u0147\u0148\7j\2\2\u0148D\3\2\2\2\u0149\u014a")
        buf.write("\7^\2\2\u014a\u014b\7e\2\2\u014b\u014c\7q\2\2\u014c\u014d")
        buf.write("\7u\2\2\u014d\u014e\7j\2\2\u014eF\3\2\2\2\u014f\u0150")
        buf.write("\7^\2\2\u0150\u0151\7v\2\2\u0151\u0152\7c\2\2\u0152\u0153")
        buf.write("\7p\2\2\u0153\u0154\7j\2\2\u0154H\3\2\2\2\u0155\u0156")
        buf.write("\7^\2\2\u0156\u0157\7c\2\2\u0157\u0158\7t\2\2\u0158\u0159")
        buf.write("\7u\2\2\u0159\u015a\7k\2\2\u015a\u015b\7p\2\2\u015b\u015c")
        buf.write("\7j\2\2\u015cJ\3\2\2\2\u015d\u015e\7^\2\2\u015e\u015f")
        buf.write("\7c\2\2\u015f\u0160\7t\2\2\u0160\u0161\7e\2\2\u0161\u0162")
        buf.write("\7q\2\2\u0162\u0163\7u\2\2\u0163\u0164\7j\2\2\u0164L\3")
        buf.write("\2\2\2\u0165\u0166\7^\2\2\u0166\u0167\7c\2\2\u0167\u0168")
        buf.write("\7t\2\2\u0168\u0169\7v\2\2\u0169\u016a\7c\2\2\u016a\u016b")
        buf.write("\7p\2\2\u016b\u016c\7j\2\2\u016cN\3\2\2\2\u016d\u016e")
        buf.write("\7^\2\2\u016e\u016f\7u\2\2\u016f\u0170\7s\2\2\u0170\u0171")
        buf.write("\7t\2\2\u0171\u0172\7v\2\2\u0172P\3\2\2\2\u0173\u0174")
        buf.write("\7^\2\2\u0174\u0175\7v\2\2\u0175\u0176\7k\2\2\u0176\u0177")
        buf.write("\7o\2\2\u0177\u0178\7g\2\2\u0178\u0179\7u\2\2\u0179R\3")
        buf.write("\2\2\2\u017a\u017b\7^\2\2\u017b\u017c\7e\2\2\u017c\u017d")
        buf.write("\7f\2\2\u017d\u017e\7q\2\2\u017e\u017f\7v\2\2\u017fT\3")
        buf.write("\2\2\2\u0180\u0181\7^\2\2\u0181\u0182\7f\2\2\u0182\u0183")
        buf.write("\7k\2\2\u0183\u0184\7x\2\2\u0184V\3\2\2\2\u0185\u0186")
        buf.write("\7^\2\2\u0186\u0187\7h\2\2\u0187\u0188\7t\2\2\u0188\u0189")
        buf.write("\7c\2\2\u0189\u018a\7e\2\2\u018aX\3\2\2\2\u018b\u018c")
        buf.write("\7^\2\2\u018c\u018d\7d\2\2\u018d\u018e\7k\2\2\u018e\u018f")
        buf.write("\7p\2\2\u018f\u0190\7q\2\2\u0190\u0191\7o\2\2\u0191Z\3")
        buf.write("\2\2\2\u0192\u0193\7^\2\2\u0193\u0194\7f\2\2\u0194\u0195")
        buf.write("\7d\2\2\u0195\u0196\7k\2\2\u0196\u0197\7p\2\2\u0197\u0198")
        buf.write("\7q\2\2\u0198\u0199\7o\2\2\u0199\\\3\2\2\2\u019a\u019b")
        buf.write("\7^\2\2\u019b\u019c\7v\2\2\u019c\u019d\7d\2\2\u019d\u019e")
        buf.write("\7k\2\2\u019e\u019f\7p\2\2\u019f\u01a0\7q\2\2\u01a0\u01a1")
        buf.write("\7o\2\2\u01a1^\3\2\2\2\u01a2\u01a3\7^\2\2\u01a3\u01a4")
        buf.write("\7o\2\2\u01a4\u01a5\7c\2\2\u01a5\u01a6\7v\2\2\u01a6\u01a7")
        buf.write("\7j\2\2\u01a7\u01a8\7k\2\2\u01a8\u01a9\7v\2\2\u01a9`\3")
        buf.write("\2\2\2\u01aa\u01ab\7a\2\2\u01abb\3\2\2\2\u01ac\u01ad\7")
        buf.write("`\2\2\u01add\3\2\2\2\u01ae\u01af\7<\2\2\u01aff\3\2\2\2")
        buf.write("\u01b0\u01b1\t\2\2\2\u01b1h\3\2\2\2\u01b2\u01b6\7f\2\2")
        buf.write("\u01b3\u01b5\5g\64\2\u01b4\u01b3\3\2\2\2\u01b5\u01b8\3")
        buf.write("\2\2\2\u01b6\u01b7\3\2\2\2\u01b6\u01b4\3\2\2\2\u01b7\u01c0")
        buf.write("\3\2\2\2\u01b8\u01b6\3\2\2\2\u01b9\u01c1\t\3\2\2\u01ba")
        buf.write("\u01bc\7^\2\2\u01bb\u01bd\t\3\2\2\u01bc\u01bb\3\2\2\2")
        buf.write("\u01bd\u01be\3\2\2\2\u01be\u01bc\3\2\2\2\u01be\u01bf\3")
        buf.write("\2\2\2\u01bf\u01c1\3\2\2\2\u01c0\u01b9\3\2\2\2\u01c0\u01ba")
        buf.write("\3\2\2\2\u01c1j\3\2\2\2\u01c2\u01c3\t\3\2\2\u01c3l\3\2")
        buf.write("\2\2\u01c4\u01c5\t\4\2\2\u01c5n\3\2\2\2\u01c6\u01c8\5")
        buf.write("m\67\2\u01c7\u01c6\3\2\2\2\u01c8\u01c9\3\2\2\2\u01c9\u01c7")
        buf.write("\3\2\2\2\u01c9\u01ca\3\2\2\2\u01ca\u01d2\3\2\2\2\u01cb")
        buf.write("\u01cc\7.\2\2\u01cc\u01cd\5m\67\2\u01cd\u01ce\5m\67\2")
        buf.write("\u01ce\u01cf\5m\67\2\u01cf\u01d1\3\2\2\2\u01d0\u01cb\3")
        buf.write("\2\2\2\u01d1\u01d4\3\2\2\2\u01d2\u01d0\3\2\2\2\u01d2\u01d3")
        buf.write("\3\2\2\2\u01d3\u01ec\3\2\2\2\u01d4\u01d2\3\2\2\2\u01d5")
        buf.write("\u01d7\5m\67\2\u01d6\u01d5\3\2\2\2\u01d7\u01da\3\2\2\2")
        buf.write("\u01d8\u01d6\3\2\2\2\u01d8\u01d9\3\2\2\2\u01d9\u01e2\3")
        buf.write("\2\2\2\u01da\u01d8\3\2\2\2\u01db\u01dc\7.\2\2\u01dc\u01dd")
        buf.write("\5m\67\2\u01dd\u01de\5m\67\2\u01de\u01df\5m\67\2\u01df")
        buf.write("\u01e1\3\2\2\2\u01e0\u01db\3\2\2\2\u01e1\u01e4\3\2\2\2")
        buf.write("\u01e2\u01e0\3\2\2\2\u01e2\u01e3\3\2\2\2\u01e3\u01e5\3")
        buf.write("\2\2\2\u01e4\u01e2\3\2\2\2\u01e5\u01e7\7\60\2\2\u01e6")
        buf.write("\u01e8\5m\67\2\u01e7\u01e6\3\2\2\2\u01e8\u01e9\3\2\2\2")
        buf.write("\u01e9\u01e7\3\2\2\2\u01e9\u01ea\3\2\2\2\u01ea\u01ec\3")
        buf.write("\2\2\2\u01eb\u01c7\3\2\2\2\u01eb\u01d8\3\2\2\2\u01ecp")
        buf.write("\3\2\2\2\u01ed\u01ee\7?\2\2\u01eer\3\2\2\2\u01ef\u01f0")
        buf.write("\7>\2\2\u01f0t\3\2\2\2\u01f1\u01f2\7^\2\2\u01f2\u01f3")
        buf.write("\7n\2\2\u01f3\u01f4\7g\2\2\u01f4\u01f5\7s\2\2\u01f5v\3")
        buf.write("\2\2\2\u01f6\u01f7\7@\2\2\u01f7x\3\2\2\2\u01f8\u01f9\7")
        buf.write("^\2\2\u01f9\u01fa\7i\2\2\u01fa\u01fb\7g\2\2\u01fb\u01fc")
        buf.write("\7s\2\2\u01fcz\3\2\2\2\u01fd\u01fe\7#\2\2\u01fe|\3\2\2")
        buf.write("\2\u01ff\u0201\7^\2\2\u0200\u0202\t\3\2\2\u0201\u0200")
        buf.write("\3\2\2\2\u0202\u0203\3\2\2\2\u0203\u0201\3\2\2\2\u0203")
        buf.write("\u0204\3\2\2\2\u0204~\3\2\2\2\17\2\u0084\u00da\u01b6\u01be")
        buf.write("\u01c0\u01c9\u01d2\u01d8\u01e2\u01e9\u01eb\u0203\3\b\2")
        buf.write("\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    ADD = 3
    SUB = 4
    MUL = 5
    DIV = 6
    L_PAREN = 7
    R_PAREN = 8
    L_BRACE = 9
    R_BRACE = 10
    L_BRACKET = 11
    R_BRACKET = 12
    BAR = 13
    FUNC_LIM = 14
    LIM_APPROACH_SYM = 15
    FUNC_INT = 16
    FUNC_SUM = 17
    FUNC_PROD = 18
    FUNC_LOG = 19
    FUNC_LN = 20
    FUNC_SIN = 21
    FUNC_COS = 22
    FUNC_TAN = 23
    FUNC_CSC = 24
    FUNC_SEC = 25
    FUNC_COT = 26
    FUNC_ARCSIN = 27
    FUNC_ARCCOS = 28
    FUNC_ARCTAN = 29
    FUNC_ARCCSC = 30
    FUNC_ARCSEC = 31
    FUNC_ARCCOT = 32
    FUNC_SINH = 33
    FUNC_COSH = 34
    FUNC_TANH = 35
    FUNC_ARSINH = 36
    FUNC_ARCOSH = 37
    FUNC_ARTANH = 38
    FUNC_SQRT = 39
    CMD_TIMES = 40
    CMD_CDOT = 41
    CMD_DIV = 42
    CMD_FRAC = 43
    CMD_BINOM = 44
    CMD_DBINOM = 45
    CMD_TBINOM = 46
    CMD_MATHIT = 47
    UNDERSCORE = 48
    CARET = 49
    COLON = 50
    DIFFERENTIAL = 51
    LETTER = 52
    NUMBER = 53
    EQUAL = 54
    LT = 55
    LTE = 56
    GT = 57
    GTE = 58
    BANG = 59
    SYMBOL = 60

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ "DEFAULT_MODE" ]

    literalNames = [ "<INVALID>",
            "','", "'+'", "'-'", "'*'", "'/'", "'('", "')'", "'{'", "'}'",
            "'['", "']'", "'|'", "'\\lim'", "'\\int'", "'\\sum'", "'\\prod'",
            "'\\log'", "'\\ln'", "'\\sin'", "'\\cos'", "'\\tan'", "'\\csc'",
            "'\\sec'", "'\\cot'", "'\\arcsin'", "'\\arccos'", "'\\arctan'",
            "'\\arccsc'", "'\\arcsec'", "'\\arccot'", "'\\sinh'", "'\\cosh'",
            "'\\tanh'", "'\\arsinh'", "'\\arcosh'", "'\\artanh'", "'\\sqrt'",
            "'\\times'", "'\\cdot'", "'\\div'", "'\\frac'", "'\\binom'",
            "'\\dbinom'", "'\\tbinom'", "'\\mathit'", "'_'", "'^'", "':'",
            "'='", "'<'", "'\\leq'", "'>'", "'\\geq'", "'!'" ]

    symbolicNames = [ "<INVALID>",
            "WS", "ADD", "SUB", "MUL", "DIV", "L_PAREN", "R_PAREN", "L_BRACE",
            "R_BRACE", "L_BRACKET", "R_BRACKET", "BAR", "FUNC_LIM", "LIM_APPROACH_SYM",
            "FUNC_INT", "FUNC_SUM", "FUNC_PROD", "FUNC_LOG", "FUNC_LN",
            "FUNC_SIN", "FUNC_COS", "FUNC_TAN", "FUNC_CSC", "FUNC_SEC",
            "FUNC_COT", "FUNC_ARCSIN", "FUNC_ARCCOS", "FUNC_ARCTAN", "FUNC_ARCCSC",
            "FUNC_ARCSEC", "FUNC_ARCCOT", "FUNC_SINH", "FUNC_COSH", "FUNC_TANH",
            "FUNC_ARSINH", "FUNC_ARCOSH", "FUNC_ARTANH", "FUNC_SQRT", "CMD_TIMES",
            "CMD_CDOT", "CMD_DIV", "CMD_FRAC", "CMD_BINOM", "CMD_DBINOM",
            "CMD_TBINOM", "CMD_MATHIT", "UNDERSCORE", "CARET", "COLON",
            "DIFFERENTIAL", "LETTER", "NUMBER", "EQUAL", "LT", "LTE", "GT",
            "GTE", "BANG", "SYMBOL" ]

    ruleNames = [ "T__0", "WS", "ADD", "SUB", "MUL", "DIV", "L_PAREN", "R_PAREN",
                  "L_BRACE", "R_BRACE", "L_BRACKET", "R_BRACKET", "BAR",
                  "FUNC_LIM", "LIM_APPROACH_SYM", "FUNC_INT", "FUNC_SUM",
                  "FUNC_PROD", "FUNC_LOG", "FUNC_LN", "FUNC_SIN", "FUNC_COS",
                  "FUNC_TAN", "FUNC_CSC", "FUNC_SEC", "FUNC_COT", "FUNC_ARCSIN",
                  "FUNC_ARCCOS", "FUNC_ARCTAN", "FUNC_ARCCSC", "FUNC_ARCSEC",
                  "FUNC_ARCCOT", "FUNC_SINH", "FUNC_COSH", "FUNC_TANH",
                  "FUNC_ARSINH", "FUNC_ARCOSH", "FUNC_ARTANH", "FUNC_SQRT",
                  "CMD_TIMES", "CMD_CDOT", "CMD_DIV", "CMD_FRAC", "CMD_BINOM",
                  "CMD_DBINOM", "CMD_TBINOM", "CMD_MATHIT", "UNDERSCORE",
                  "CARET", "COLON", "WS_CHAR", "DIFFERENTIAL", "LETTER",
                  "DIGIT", "NUMBER", "EQUAL", "LT", "LTE", "GT", "GTE",
                  "BANG", "SYMBOL" ]

    grammarFileName = "LaTeX.g4"

    def __init__(self, input=None, output:TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.7.1")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


